# vim:ft=kitty

## name: Rumda Dark x Rainy Keyboard
## author: Tanakorn

background            #1C1612
foreground            #E9F3FB
selection_background  #382C24
selection_foreground  #E9F3FB
cursor                #9890D0
cursor_text_color     #1C1612

url_color             #9AC2CB

active_border_color   #817BBE
inactive_border_color #423E63

active_tab_background   #817BBE
active_tab_foreground   #1C1612
inactive_tab_background #28201A
inactive_tab_foreground #6C769F

# Normal colors
color0  #1C1612
color1  #db6657
color2  #9AC2CB
color3  #d89371
color4  #9CADCF
color5  #817BBE
color6  #9AC2CB
color7  #D0DBE6

# Bright colors
color8  #423E63
color9  #f07178
color10 #b5e2da
color11 #f5d08b
color12 #C5D3E0
color13 #9890D0
color14 #E7F3FD
color15 #E9F3FB
