# Kitty Terminal Configuration

font_family      MesloLGS Nerd Font Mono
font_size        12.0

background_opacity 1.0
confirm_os_window_close 0
window_padding_width 10
enable_audio_bell no

# Features & UX
cursor_trail 3
copy_on_select yes

# Shell
shell /usr/bin/zsh


# BEGIN_KITTY_THEME
# Monochrome Minimal
include current-theme.conf
# END_KITTY_THEME