
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


-------------------
---- HOST LAYER ----
-------------------

-- Everything tied to one physical laptop -- panel modes, monitor descriptions,
-- WORKSPACE_COUNT -- lives in hosts/<id>/hypr.lua, reached through the
-- .config/hypr/hosts symlink. See hosts/README.md.
--
-- The id comes from ~/.config/dotfiles-host when pinned, otherwise from a slug
-- of the DMI vendor and model, so a fresh clone works before anything is set up.

local function read_first_line(path)
    local f = io.open(path, "r")
    if not f then
        return nil
    end
    local line = f:read("l")
    f:close()
    if line == nil or line == "" then
        return nil
    end
    return line
end

local function slugify(value)
    return (value:lower():gsub("[^a-z0-9]+", "-"):gsub("^%-+", ""):gsub("%-+$", ""))
end

local function resolve_host_id()
    local env = os.getenv("DOTFILES_HOST")
    if env and env ~= "" then
        return env
    end

    local config_home = os.getenv("XDG_CONFIG_HOME") or ((os.getenv("HOME") or "") .. "/.config")
    local pinned = read_first_line(config_home .. "/dotfiles-host")
    if pinned then
        return pinned
    end

    local dmi = "/sys/devices/virtual/dmi/id/"
    local vendor = read_first_line(dmi .. "sys_vendor")
    local model = read_first_line(dmi .. "product_name") or read_first_line(dmi .. "board_name")
    if not model then
        return nil
    end

    -- Skip the vendor prefix when the model already names the manufacturer.
    if vendor and not model:lower():find(vendor:lower(), 1, true) then
        model = vendor .. " " .. model
    end
    return slugify(model)
end

-- Defaults, so an unconfigured machine still comes up with a usable desktop.
WORKSPACE_COUNT = 5
HOST_ID = resolve_host_id()

local host_loaded = false
if HOST_ID then
    host_loaded = pcall(require, "hosts." .. HOST_ID .. ".hypr")
end

if not host_loaded then
    -- No layer for this machine yet: let every output self-configure.
    hl.monitor({
        output   = "",
        mode     = "preferred",
        position = "auto",
        scale    = 1,
    })
end


--------------------------------------
---- WORKSPACE MONITOR ASSIGNMENT ----
--------------------------------------

-- No monitor pinning: the workspaces follow whatever display is connected, so
-- the same config works on the laptop alone and with an external monitor.
-- WORKSPACE_COUNT comes from the host layer above.
for i = 1, WORKSPACE_COUNT do
    hl.workspace_rule({
        workspace = tostring(i),
    })
end


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local HOME = os.getenv("HOME") or "/home/kp"

local function is_file_exists(name)
    local f = io.open(name, "r")
    if f ~= nil then
        io.close(f)
        return true
    else
        return false
    end
end

pcall(require, "hyprland.lib")
pcall(require, "hyprland.variables")
if is_file_exists(HOME .. "/.config/hypr/custom/variables.lua") then
    pcall(require, "custom.variables")
end

local function workspace_in_group(i)
    return i
end

local terminal = "kitty"
local fileManager = os.getenv("FILEMANAGER") or ("xdg-open " .. HOME)
local menu = "pkill fuzzel || fuzzel"
local browser = "google-chrome-stable"
local codeEditor = "cursor"
local volumeMixer = "pavucontrol"
local taskManager = "btop"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
-- This runs on both initial config load and reload. Every command is guarded so
-- reloading Hyprland cannot create duplicate background services.
local function ensure_desktop_services()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE; systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("hyprctl plugins list | grep -q 'Plugin GloView' || hyprctl plugin load /usr/lib/gloview.so")
    -- The wrapper takes an flock, so a second call is a no-op instead of a second bar.
    hl.exec_cmd(HOME .. "/.local/bin/waybar")
    hl.exec_cmd("pgrep -x swaync || swaync")
    hl.exec_cmd("pgrep -x hypridle || hypridle")
    -- Watches AC state and the battery level; its own flock makes this a no-op
    -- when one is already running.
    hl.exec_cmd(HOME .. "/.local/bin/battery-saver daemon")
    -- Start wallpaper daemon once; seed a wallpaper only on that first start
    -- so Hyprland reload does not reshuffle the current image.
    hl.exec_cmd("if ! pgrep -x awww-daemon >/dev/null; then awww-daemon; " .. HOME .. "/.config/hypr/scripts/set-wallpaper.sh; fi")
    hl.exec_cmd("pgrep -x kanshi || kanshi")
    hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
    hl.exec_cmd("pgrep -f nm-applet || nm-applet --indicator")
    hl.exec_cmd("pgrep -x blueman-applet || blueman-applet")
    hl.exec_cmd("pgrep -f 'wl-paste --type text --watch cliphist store' || wl-paste --type text --watch cliphist store")
    hl.exec_cmd("pgrep -f 'wl-paste --type image --watch cliphist store' || wl-paste --type image --watch cliphist store")
    hl.exec_cmd("pgrep -x easyeffects || easyeffects --service-mode")
    hl.exec_cmd("for c in 0 1 2 3; do amixer -c $c sset 'Mic Boost' 1 2>/dev/null; done || true")
end

ensure_desktop_services()
pcall(hl.on, "hyprland.start", ensure_desktop_services)
pcall(hl.on, "config.reloaded", ensure_desktop_services)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

local currentPath = os.getenv("PATH") or "/usr/local/bin:/usr/bin:/bin"
local localBin = HOME .. "/.local/bin"
if not string.find(currentPath, localBin, 1, true) then
    currentPath = localBin .. ":" .. currentPath
end

hl.env("PATH", currentPath)
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
-- Hybrid Intel + NVIDIA (MSI GF63): do not force LIBVA / NVIDIA GLX globally.
-- That often breaks Chrome GPU / VAAPI. Leave Intel as the default for UI apps.


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 4,
        gaps_out = 8,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(9890D0ff)", "rgba(817BBEff)"}, angle = 45 },
            inactive_border = "rgba(423E63ff)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 12,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        dim_inactive = true,
        dim_strength = 0.1,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = false,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 3.5, bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 3.5, bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 3.5, bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 2,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 2,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,    -- Disable default anime mascot wallpapers
        disable_hyprland_logo   = true, -- Disable Hyprland logo & mascot background
        disable_splash_rendering = true,
        focus_on_activate       = false,
        enable_swallow          = true,
        swallow_regex           = "^(kitty)$",
        mouse_move_enables_dpms = true,
        key_press_enables_dpms  = true,
    },
})

------------------
----  CURSOR  ----
------------------

hl.config({
    cursor = {
        no_warps = false,
        warp_on_change_workspace = 1,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us,th",
        kb_variant = "",
        kb_model   = "",
        kb_options = "grp:win_space_toggle",
        kb_rules   = "",

        repeat_rate  = 50,
        repeat_delay = 300,

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
            tap = true,
            disable_while_typing = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

-- Daily map is ported from the previous keybinds.conf. Testdot extras are
-- added only on keys that file did not use.

local lockScript = HOME .. "/.config/hypr/scripts/lock.sh"
local wallpaperScript = HOME .. "/.config/hypr/scripts/set-wallpaper.sh"
local clipboardMenu = "pkill fuzzel || cliphist list | fuzzel --match-mode fzf --dmenu | cliphist decode | wl-copy"

--##! Apps (original Super+... map)
hl.bind("SUPER + Return", hl.dsp.exec_cmd(terminal), { description = "App: Terminal (Kitty)" })
hl.bind("SUPER + B", hl.dsp.exec_cmd(browser), { description = "App: Browser (Chrome)" })
hl.bind("SUPER + C", hl.dsp.exec_cmd(codeEditor), { description = "App: Editor (Cursor)" })
hl.bind("SUPER + D", hl.dsp.exec_cmd(menu), { description = "App: Launcher (Fuzzel)" })
hl.bind("SUPER + E", hl.dsp.exec_cmd(fileManager), { description = "App: Open home folder" })
hl.bind("SUPER + Q", hl.dsp.window.close(), { description = "Window: Close" })
hl.bind("SUPER + M", hl.dsp.exec_cmd("pkill wlogout || wlogout -p layer-shell || powermenu"), { description = "Session: Logout menu" })
hl.bind("SUPER + V", hl.dsp.exec_cmd(clipboardMenu), { description = "Utilities: Clipboard history" })
hl.bind("SUPER + L", hl.dsp.exec_cmd(lockScript), { description = "Session: Lock" })
hl.bind("SUPER + N", hl.dsp.exec_cmd("swaync-client -t -sw"), { description = "Shell: Notification center" })
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Window: Fullscreen" })
hl.bind("SUPER + T", hl.dsp.window.float({ action = "toggle" }), { description = "Window: Toggle floating" })
hl.bind("SUPER + P", hl.dsp.exec_cmd("hyprctl dispatch pseudo"), { description = "Window: Pseudo" })
hl.bind("SUPER + SHIFT + J", hl.dsp.exec_cmd("hyprctl dispatch layoutmsg togglesplit"), { description = "Layout: Toggle dwindle split" })

--##! Focus — vim-ish (L is lock, so right uses semicolon)
hl.bind("SUPER + H", hl.dsp.focus({ direction = "l" }), { description = "Window: Focus left" })
hl.bind("SUPER + J", hl.dsp.focus({ direction = "d" }), { description = "Window: Focus down" })
hl.bind("SUPER + K", hl.dsp.focus({ direction = "u" }), { description = "Window: Focus up" })
hl.bind("SUPER + Semicolon", hl.dsp.focus({ direction = "r" }), { description = "Window: Focus right" })

--##! Move window — Super+arrows (and vim counterparts that do not steal lock)
hl.bind("SUPER + Left", hl.dsp.window.move({ direction = "l" }), { description = "Window: Move left" })
hl.bind("SUPER + Right", hl.dsp.window.move({ direction = "r" }), { description = "Window: Move right" })
hl.bind("SUPER + Up", hl.dsp.window.move({ direction = "u" }), { description = "Window: Move up" })
hl.bind("SUPER + Down", hl.dsp.window.move({ direction = "d" }), { description = "Window: Move down" })
hl.bind("SUPER + SHIFT + Left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + Right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + Up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + Down", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + Semicolon", hl.dsp.window.move({ direction = "r" }))

--##! Workspaces 1-10
for i = 1, WORKSPACE_COUNT do
    hl.bind("SUPER + " .. (i % 10), function()
        hl.dispatch(hl.dsp.focus({ workspace = workspace_in_group(i) }))
    end, { description = "Workspace: Focus " .. i })
    hl.bind("SUPER + SHIFT + " .. (i % 10), function()
        hl.dispatch(hl.dsp.window.move({ workspace = workspace_in_group(i), follow = true }))
    end, { description = "Window: Move to workspace " .. i })
end

hl.bind("SUPER + comma", hl.dsp.focus({ workspace = "e-1" }), { description = "Workspace: Previous" })
hl.bind("SUPER + period", hl.dsp.focus({ workspace = "e+1" }), { description = "Workspace: Next" })
hl.bind("SUPER + SHIFT + comma", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + SHIFT + period", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true, description = "Window: Move" })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Window: Resize" })

--##! Media / brightness (hardware keys)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.5"), { locked = true, repeating = true, description = "Audio: Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true, description = "Audio: Volume down" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, description = "Audio: Toggle mute" })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Media: Play/pause" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true, description = "Media: Next" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true, description = "Media: Previous" })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true, description = "Brightness: Up" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true, description = "Brightness: Down" })

--##! Screenshots & wallpaper (original Print map)
hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp)" - | wl-copy'), { description = "Utilities: Region screenshot >> clipboard" })
hl.bind("SUPER + Print", hl.dsp.exec_cmd("grim - | wl-copy"), { description = "Utilities: Fullscreen screenshot >> clipboard" })
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd(wallpaperScript .. " random"), { description = "Shell: Random wallpaper" })

-- Lid close: lock, then blank (not ignored)
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd(lockScript .. " --blank"), { locked = true })

--##! Testdot extras on unused keys only
hl.bind("SUPER + slash", hl.dsp.exec_cmd("hotkey-cheatsheet"), { description = "Helper: Hotkeys cheat sheet" })
hl.bind("SUPER + question", hl.dsp.exec_cmd("hotkey-cheatsheet"), { description = "Helper: Hotkeys cheat sheet" })
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("pidof slurp || smart-snip"), { description = "Utilities: Smart snip (copy / swappy)" })
hl.bind("SUPER + SHIFT + X", hl.dsp.exec_cmd("pidof slurp || ocr-snip"), { description = "Utilities: OCR Thai+English >> clipboard" })
hl.bind("SUPER + F10", hl.dsp.exec_cmd("audio-switch"), { description = "Audio: Switch output device" })
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("theme-switcher toggle"), { description = "Shell: Toggle dark / light theme" })
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"), { description = "Utilities: Color picker" })
hl.bind("CTRL + SUPER + B", hl.dsp.exec_cmd("battery-saver toggle"), { description = "Shell: Toggle battery saver" })
hl.bind("CTRL + SUPER + R", hl.dsp.exec_cmd("hyprctl reload && pkill -x waybar"), { description = "Shell: Reload Hyprland & bar" })
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("kitty -e yazi"), { description = "App: Yazi file manager" })
hl.bind("CTRL + SUPER + V", hl.dsp.exec_cmd(volumeMixer), { description = "App: Volume mixer" })
hl.bind("CTRL + SHIFT + Escape", hl.dsp.exec_cmd("kitty -e " .. taskManager), { description = "App: Task manager" })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Float Steam popups, chat, and subwindows
hl.window_rule({
    name  = "auto-float-steam-dialogs",
    match = {
        class = "^(steam|Steam)$",
        title = "^(Friends List|Steam - News|Settings|Music Player|Screenshot Manager|Steam Guard|Compact Mode)$",
    },
    float = true,
})

-- Auto-Float Utility Dialogs & System Popups
hl.window_rule({
    name  = "auto-float-utilities",
    match = {
        class = "^(pavucontrol|org.pulseaudio.pavucontrol|nm-connection-editor|blueman-manager|gnome-calculator|org.gnome.Calculator|feh|imv|mpv|file-roller|nwg-look|qt5ct|qt6ct|waypaper|wlogout)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name  = "auto-float-dialogs",
    match = {
        title = "^(Open File|Select a File|Choose Files|Save As|Confirm to replace|File Operation Progress)$",
    },
    float = true,
    center = true,
})

-- Picture-in-Picture Floating & Pinning
hl.window_rule({
    name  = "pip-window",
    match = { title = "^(Picture-in-Picture|Picture in picture)$" },
    float = true,
    pin   = true,
    no_initial_focus = true,
    suppress_event   = "activate",
})

-- Dropdown Scratchpad Terminal Rules
hl.workspace_rule({
    workspace = "special:terminal",
    on_created_empty = "kitty --class scratchpad-term",
})

hl.window_rule({
    name  = "scratchpad-term-rule",
    match = { class = "^scratchpad-term$" },
    float = true,
    size  = { "80%", "75%" },
    center = true,
})
