# Theme: Dracula
# By: Dracula Theme

theme[main_bg]="#282a36"
theme[main_fg]="#f8f8f2"
theme[title]="#f8f8f2"
theme[hi_fg]="#8be9fd"
theme[selected_bg]="#44475a"
theme[selected_fg]="#bd93f9"
theme[inactive_fg]="#6272a4"
theme[graph_text]="#f8f8f2"
theme[proc_misc]="#ff79c6"
theme[cpu_box]="#bd93f9"
theme[mem_box]="#50fa7b"
theme[net_box]="#ff79c6"
theme[proc_box]="#8be9fd"
theme[div_line]="#44475a"

theme[temp_start]="#50fa7b"
theme[temp_mid]="#f1fa8c"
theme[temp_end]="#ff5555"

theme[cpu_start]="#50fa7b"
theme[cpu_mid]="#f1fa8c"
theme[cpu_end]="#ff5555"

theme[free_start]="#50fa7b"
theme[free_mid]="#f1fa8c"
theme[free_end]="#ff5555"

theme[cached_start]="#8be9fd"
theme[cached_mid]="#bd93f9"
theme[cached_end]="#ff79c6"

theme[available_start]="#50fa7b"
theme[available_mid]="#f1fa8c"
theme[available_end]="#ff5555"

theme[used_start]="#ff5555"
theme[used_mid]="#ff79c6"
theme[used_end]="#bd93f9"

theme[download_start]="#bd93f9"
theme[download_mid]="#8be9fd"
theme[download_end]="#50fa7b"

theme[upload_start]="#ff79c6"
theme[upload_mid]="#f1fa8c"
theme[upload_end]="#ff5555"

theme[process_start]="#bd93f9"
theme[process_mid]="#8be9fd"
theme[process_end]="#ff79c6"
